/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamlinedgradingsystem;

import ca.sfu.cmpt275.deliverable.colinq.*;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.event.*;
import java.awt.*;
import java.util.*;

/**
 *
 * @author jsargent
 */
public class CreateActivity extends JFrame{
    private User userModel;
    private Course courseModel;
   
//    Vector vt;
    /**
     * Creates new form CreateActivity
     */
    public CreateActivity(User userModel, Course courseModel) {
        this.userModel = userModel;
        this.courseModel = courseModel;        
        initComponents();
//        CreateCourse course = new CreateCourse();
  //       courseComboBx.addItem(course.vt);
        
    }
    
    Activity activity;
    String actName;
    String solPath;
    String language;
    String subPath;
    Date dueDate;
//    Rubric actRubric;
    String answerKey;
    int type;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createProgrammingButton = new javax.swing.JRadioButton();
        createProblemSetButton = new javax.swing.JRadioButton();
        createEssayButton = new javax.swing.JRadioButton();
        createMultiChoiceButton = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create an activity");

        createProgrammingButton.setText("Programming Activity");
        createProgrammingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProgrammingButtonActionPerformed(evt);
            }
        });

        createProblemSetButton.setText("Problem Set");
        createProblemSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProblemSetButtonActionPerformed(evt);
            }
        });

        createEssayButton.setText("Essay");
        createEssayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEssayButtonActionPerformed(evt);
            }
        });

        createMultiChoiceButton.setText("Multiple Choice");
        createMultiChoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMultiChoiceButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Please select an activity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createProgrammingButton)
                            .addComponent(createEssayButton)
                            .addComponent(createMultiChoiceButton)
                            .addComponent(createProblemSetButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(createProgrammingButton)
                .addGap(18, 18, 18)
                .addComponent(createProblemSetButton)
                .addGap(18, 18, 18)
                .addComponent(createEssayButton)
                .addGap(18, 18, 18)
                .addComponent(createMultiChoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProgrammingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProgrammingButtonActionPerformed
        
        type = 1;
       
         
    }//GEN-LAST:event_createProgrammingButtonActionPerformed

    private void createProblemSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProblemSetButtonActionPerformed
       
        type = 2;
      
        
    }//GEN-LAST:event_createProblemSetButtonActionPerformed

    private void createEssayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEssayButtonActionPerformed
        
        type = 3;
      
       
    }//GEN-LAST:event_createEssayButtonActionPerformed

    private void createMultiChoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMultiChoiceButtonActionPerformed
        
        type = 4;
        
                     
    }//GEN-LAST:event_createMultiChoiceButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
       switch(type){
           case 1:  new CreateProgrammingActivity(userModel, courseModel).setVisible(true);
                    this.setVisible(false);
                    break;
               
           case 2:  new CreateProblemSetActivity(userModel, courseModel).setVisible(true);
                    this.setVisible(false);
                    break;
           
           case 3:  new CreateEssayActivity(userModel, courseModel).setVisible(true);
                    this.setVisible(false);
                    break;
             
           case 4:  
                    new CreateMultipleChoiceActivity(userModel, courseModel).setVisible(true);
                    this.setVisible(false);
                    break;
       
       }
       
           
            
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        new ManageActivitiesGUI(userModel, courseModel).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton createEssayButton;
    private javax.swing.JRadioButton createMultiChoiceButton;
    private javax.swing.JRadioButton createProblemSetButton;
    private javax.swing.JRadioButton createProgrammingButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
