/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamlinedgradingsystem;

import ca.sfu.cmpt275.deliverable.colinq.*;
import ca.sfu.cmpt275.deliverable.telunc.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

    
/**
 *
 * @author jsargent
 */
public class CreateMultipleChoiceActivity extends javax.swing.JFrame {
    private User userModel;
    private Course courseModel;
    
    
    
    int actID;
    String actName;
    String solPath;
    String actType;
    String language;
    String subPath;
    String dueDate;
    int courseid;
    String answerKey;
    DateFormat format;
    boolean createRubric = false;
    String sqlString1;
    Activity multipleChoice;
    
    /**
     * Creates new form CreateMultipleChoiceActivity
     */
    public CreateMultipleChoiceActivity(User userModel, Course courseModel) {
        this.courseModel = courseModel;
        this.userModel = userModel;
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        solutionKey = new javax.swing.JTextField();
        actLanguage = new javax.swing.JTextField();
        submissionPathField = new javax.swing.JTextField();
        dueDateLabel = new javax.swing.JTextField();
        answerkeyField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create Multiple Choice Activity");

        jLabel2.setText("Activity Name:");

        jLabel3.setText("Solution Key:");

        jLabel5.setText("Language:");

        jLabel6.setText("Submission Path:");

        jLabel7.setText("Due Date:");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Answer Key:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        solutionKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionKeyActionPerformed(evt);
            }
        });

        actLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actLanguageActionPerformed(evt);
            }
        });

        submissionPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionPathFieldActionPerformed(evt);
            }
        });

        dueDateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueDateLabelActionPerformed(evt);
            }
        });

        answerkeyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerkeyFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(solutionKey)
                            .addComponent(actLanguage)
                            .addComponent(submissionPathField)
                            .addComponent(dueDateLabel)
                            .addComponent(answerkeyField)))
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(solutionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(actLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submissionPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerkeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
     
    }//GEN-LAST:event_nameFieldActionPerformed

    private void solutionKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionKeyActionPerformed
     
    }//GEN-LAST:event_solutionKeyActionPerformed

    private void actLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actLanguageActionPerformed
        
    }//GEN-LAST:event_actLanguageActionPerformed

    private void submissionPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionPathFieldActionPerformed
        
    }//GEN-LAST:event_submissionPathFieldActionPerformed

    private void dueDateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueDateLabelActionPerformed
//        try{
//            dueDate = format.parse(dueDateLabel.getText());
//        }
//        catch (ParseException e){
//            e.printStackTrace();
//        }
        dueDate = dueDateLabel.getText();
    }//GEN-LAST:event_dueDateLabelActionPerformed

    private void answerkeyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerkeyFieldActionPerformed
        
    }//GEN-LAST:event_answerkeyFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        actName = nameField.getText();
        language = actLanguage.getText();
        dueDate = dueDateLabel.getText();
//        solPath = "";
        subPath = submissionPathField.getText();
        actType = ca.sfu.cmpt275.deliverable.colinq.Activity.MULTIPLECHOICE_TYPE;
        actID = -1;
        answerKey = answerkeyField.getText();
        
        String sUsername = "c275g11";
	String sPassword = "bL344y3Emh2dPtaT";
        String connectionUrl = "jdbc:sqlserver://cypress;" + "user = " + sUsername + ";" + "password = " + sPassword;
 	 
        Connection conn = null;
	Statement stmt = null;

        
        
            try{
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String sql;
            
                    conn = DriverManager.getConnection(connectionUrl);
                    stmt = conn.createStatement();
                    
                    generateUniqueRandomActID(stmt);
                    sql = "insert into Activity "
                            + "values(" + actID + ", " + courseModel.getCourseID() +  
                            ", '" + actName + "', '" + actType + "', '" + dueDate + "','" + 
                            language + "', '" + subPath + "', '" + 0 + "','" + answerKey + "')";
                    
                    //" + activityID + ",
                    
                    
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"add item success","success", JOptionPane.INFORMATION_MESSAGE);

                    stmt.close();
                    conn.close();
            }
            catch(SQLException se){
                    //Handle errors for JDBC
                    JOptionPane.showMessageDialog(null,se,"SQLException", JOptionPane.INFORMATION_MESSAGE);
                    se.printStackTrace();
            }catch(Exception e){
                    //Handle errors for Class.forName
                    JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
                    e.printStackTrace();
            }
            if(createRubric) {
                new CreateRubric(actID).setVisible(true);
                JOptionPane.showMessageDialog(null,"add rubric success","success", JOptionPane.INFORMATION_MESSAGE);
            }
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new CreateActivity(userModel, courseModel).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed
    
    private void generateUniqueRandomActID(Statement stmt) {
        try {
            actID = generateRandomID();
            String getActID_sql = "SELECT activityID FROM Activity WHERE courseID = " + 
                    courseModel.getCourseID() + " AND activityID = " + actID;
            ResultSet rs = stmt.executeQuery(getActID_sql);
            int resultCounter = 0;
            System.out.println("ActID is: " + actID);
            while(rs.next()) {
                resultCounter++;    
            }
            if(resultCounter > 0) {
                generateUniqueRandomActID(stmt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateProgrammingActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int generateRandomID() {
        Random rand = new Random();
        int randomID = rand.nextInt(Integer.MAX_VALUE) + 10;
        return randomID;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actLanguage;
    private javax.swing.JTextField answerkeyField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dueDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField solutionKey;
    private javax.swing.JTextField submissionPathField;
    // End of variables declaration//GEN-END:variables
}
