/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamlinedgradingsystem;

import ca.sfu.cmpt275.deliverable.colinq.Activity;
import ca.sfu.cmpt275.deliverable.colinq.Course;
import ca.sfu.cmpt275.deliverable.colinq.User;
import ca.sfu.cmpt275.deliverable.telunc.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jsargent
 */
public class CreateProblemSetActivity extends javax.swing.JFrame {

    private User userModel;
    private Course courseModel;
    
    String actName;
    String solPath;
    String actType;
    String language;
    String subPath;
    String dueDate;
    int actID;
//    Rubric actRubric;
//    int courseid;    
    DateFormat format;
    boolean createRubric = false;
    String sqlString1;
//    Activity problem;
    
    /**
     * Creates new form ProblemSetForm
     */
    public CreateProblemSetActivity(User userModel, Course courseModel) {
        this.userModel = userModel;
        this.courseModel = courseModel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        solutionPathField = new javax.swing.JTextField();
        actLanguage = new javax.swing.JTextField();
        dueDateLabel = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        submissionPath = new javax.swing.JTextField();
        createRubricButton = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Activity Name:");

        jLabel2.setText("Model Solution:");

        jLabel3.setText("Language:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Create Problem Set Activity");

        jLabel5.setText("Submission Path:");

        jLabel6.setText("Due Date:");

        jLabel7.setText("Create Rubric:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        solutionPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionPathFieldActionPerformed(evt);
            }
        });

        actLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actLanguageActionPerformed(evt);
            }
        });

        dueDateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueDateLabelActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submissionPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionPathActionPerformed(evt);
            }
        });

        createRubricButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRubricButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(solutionPathField)
                            .addComponent(actLanguage)
                            .addComponent(submissionPath)
                            .addComponent(dueDateLabel)
                            .addComponent(createRubricButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(solutionPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(actLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submissionPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(createRubricButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        
    }//GEN-LAST:event_nameFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       new CreateActivity(userModel, courseModel).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void solutionPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionPathFieldActionPerformed
        
    }//GEN-LAST:event_solutionPathFieldActionPerformed

    private void actLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actLanguageActionPerformed
        
    }//GEN-LAST:event_actLanguageActionPerformed

    private void dueDateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueDateLabelActionPerformed

    }//GEN-LAST:event_dueDateLabelActionPerformed

    private void submissionPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionPathActionPerformed
     
    }//GEN-LAST:event_submissionPathActionPerformed
                              

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        actName = nameField.getText();
        language = actLanguage.getText();
        dueDate = dueDateLabel.getText();
        solPath = solutionPathField.getText();
        subPath = submissionPath.getText();
        actType = Activity.PROBLEMSET_TYPE;
        actID = -1;
        String sUsername = "c275g11";
        String sPassword = "bL344y3Emh2dPtaT";
        String connectionUrl = "jdbc:sqlserver://cypress;" + "user = " + sUsername + ";" + "password = " + sPassword;

        Connection conn = null;
        Statement stmt = null;

        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String sql;

            conn = DriverManager.getConnection(connectionUrl);
            stmt = conn.createStatement();

            generateUniqueRandomActID(stmt);
            sql = "insert into Activity "
            + "values(" + actID + ", " + courseModel.getCourseID() +
            ", '" + actName + "', '" + actType + "', '" + dueDate + "','" +
            language + "', '" + subPath + "', '" + 0 + "','" + solPath + "')";

            //" + activityID + ",

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"add item success","success", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();
            
            if(createRubric) {
                new CreateRubric(actID).setVisible(true);
            }
        }
        catch(SQLException se){
            //Handle errors for JDBC
            JOptionPane.showMessageDialog(null,se,"SQLException", JOptionPane.INFORMATION_MESSAGE);
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_createButtonActionPerformed

    private void createRubricButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRubricButtonActionPerformed
        createRubric = true;

    }//GEN-LAST:event_createRubricButtonActionPerformed

    private void generateUniqueRandomActID(Statement stmt) {
        try {
            actID = generateRandomID();
            String getActID_sql = "SELECT activityID FROM Activity WHERE courseID = " + 
                    courseModel.getCourseID() + " AND activityID = " + actID;
            ResultSet rs = stmt.executeQuery(getActID_sql);
            int resultCounter = 0;
            System.out.println("ActID is: " + actID);
            while(rs.next()) {
                resultCounter++;    
            }
            if(resultCounter > 0) {
                generateUniqueRandomActID(stmt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateProgrammingActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int generateRandomID() {
        Random rand = new Random();
        int randomID = rand.nextInt(Integer.MAX_VALUE) + 10;
        return randomID;
    }
    /**
     * @param args the command line arguments
     */
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actLanguage;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JCheckBox createRubricButton;
    private javax.swing.JTextField dueDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField solutionPathField;
    private javax.swing.JTextField submissionPath;
    // End of variables declaration//GEN-END:variables
}
