/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streamlinedgradingsystem;

import java.io.File;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import ca.sfu.cmpt275.deliverable.colinq.*;

/**
 *
 * @author liufanl
 */
public class GradingProblemSet extends javax.swing.JFrame {

    private boolean isrowselected = false;
    private int selectedGradeID;
    private Double Grade;
    private int MaxGrade;
    private int selectedActivityID;
    private int selectedstudentID;
    private String a;
    
    private int studentID;
    private User userModel;
    private Course courseModel;
    private Activity activityModel;
    
    
    /**
     * Creates new form Grading
     */
    public GradingProblemSet(User userModel,Course courseModel,Activity activityModel,int studentID) {
        this.userModel=userModel;
        this.courseModel=courseModel;
        this.activityModel=activityModel;
        this.selectedstudentID = studentID;
        //System.out.println("##### selectedstudentID " +selectedstudentID );
        initComponents();
        activityModel.display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ReviewGrade = new javax.swing.JButton();
        SubmissionOpen = new javax.swing.JButton();
        SolutionOpen = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GradeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        GradeField = new javax.swing.JTextField();
        SaveGrade1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Grading Problem Set");

        ReviewGrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReviewGrade.setText("Refresh & View");
        ReviewGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewGradeActionPerformed(evt);
            }
        });

        SubmissionOpen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubmissionOpen.setText("Open Submission");
        SubmissionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmissionOpenActionPerformed(evt);
            }
        });

        SolutionOpen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SolutionOpen.setText("Open Solution");
        SolutionOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolutionOpenActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Grading Table:");

        GradeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Grade ID", "Rubric Item ID", "Rubric Item", "Max Grade", "Earned Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GradeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GradeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GradeTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Plaease Enter Grade:");

        GradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeFieldActionPerformed(evt);
            }
        });

        SaveGrade1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveGrade1.setText("Save");
        SaveGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveGrade1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GradeField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(SaveGrade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GradeField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaveGrade1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubmissionOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(SolutionOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ReviewGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SolutionOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmissionOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReviewGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeFieldActionPerformed

    private void ReviewGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewGradeActionPerformed
         // TODO add your handling code here:
        selectedActivityID = activityModel.getActivityID();
        System.out.println("****-----**activityID:"+selectedActivityID);
        System.out.println("**----***studentID:"+selectedstudentID);
        
        String DB_URL = "jdbc:sqlserver://cypress;";
        String USER = "c275g11";
        String PASS = "bL344y3Emh2dPtaT";
        Connection conn = null;
        Statement stmt = null;
         
        try{
                        
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        conn = DriverManager.getConnection(DB_URL,USER,PASS);
                        String sql;
                        sql="select G.GradeID, R.rubricItemText, R.rubricItemValue, G.earnedGrade from RubricItem R inner join Grade G on R.rubricItemID = G.rubricItemID where activityID="+selectedActivityID+"AND studentID="+selectedstudentID+"";
                        System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
                        stmt = conn.createStatement();
                        ResultSet rs = stmt.executeQuery(sql);
                        GradeTable.setModel(DbUtils.resultSetToTableModel(rs));
                        rs.close();
                        stmt.close();
                        conn.close();
                        
        }
        catch(SQLException se){
                        //Handle errors for JDBC
                        JOptionPane.showMessageDialog(null,se,"SQLException", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
                        //Handle errors for Class.forName
                        JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ReviewGradeActionPerformed

    private void SaveGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveGrade1ActionPerformed
        
        if(isrowselected == true){
            String DB_URL = "jdbc:sqlserver://cypress;";
            String USER = "c275g11";
            String PASS = "bL344y3Emh2dPtaT";
            Connection conn = null;
            Statement stmt = null;
            
            
            
            try{
                Grade = Double.parseDouble(GradeField.getText());
                System.out.println("grade is "+Grade);
            }
            catch(Exception e){
                //Handle errors for Class.forName
                JOptionPane.showMessageDialog(null,"Please enter a float grade","Empty Grade", JOptionPane.INFORMATION_MESSAGE);
                return;
                                
            }

            if (Grade < 0){
                JOptionPane.showMessageDialog(null,"Please enter a float grade not less than 0","Wrong Grade", JOptionPane.INFORMATION_MESSAGE);
                return;       
            }               
            
            

            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection(DB_URL,USER,PASS);
                String sql;                           
                sql="update Grade set earnedGrade ="+ Grade +"where gradeID =" + selectedGradeID + "";
                stmt = conn.createStatement();                           
                stmt.executeUpdate(sql); 
                stmt.close();
                conn.close();
                isrowselected = false;

            }
            catch(SQLException se){
                            //Handle errors for JDBC
                            JOptionPane.showMessageDialog(null,se,"SQLException", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                            //Handle errors for Class.forName
                            JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
            }
               
            JOptionPane.showMessageDialog(null,"Grade is successfully saved!","Success", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Please select a item (row) in the table","Error", JOptionPane.INFORMATION_MESSAGE);
        }
    
    }//GEN-LAST:event_SaveGrade1ActionPerformed

    private void SubmissionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmissionOpenActionPerformed

              
        
        String DB_URL = "jdbc:sqlserver://cypress;";
        String USER = "c275g11";
        String PASS = "bL344y3Emh2dPtaT";
        Connection conn = null;
        Statement stmt = null;
        
        System.out.println("********activityID:"+selectedActivityID);
        System.out.println("********studentID:"+selectedstudentID);
        
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection(DB_URL,USER,PASS);
                String sql;                           
                sql="select pathToSubmissions from IndividualSubmission where activityID="+selectedActivityID+"AND studentID="+selectedstudentID+"";
                stmt = conn.createStatement();     
                ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
                    System.out.println("I am here ");
                    a = rs.getString("pathToSubmissions");
                }
                stmt.close();
                conn.close();

            }
            catch(SQLException se){
                            //Handle errors for JDBC
                            JOptionPane.showMessageDialog(null,se,"SQLException", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                            //Handle errors for Class.forName
                            JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
            }
        

        
        System.out.println(a);
        String a_new = a.replace("\\","\\\\");
        System.out.println(a_new);

            try{
                //Runtime.getRuntime().exec("rund1132 url.dll,FileprotocolHandler "+"U:\\CMPT150\\f2-sample.pdf");
                //Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + a.replaceAll("\\","\\\\")); 
                    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + a_new);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e,"exception", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_SubmissionOpenActionPerformed

    private void SolutionOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolutionOpenActionPerformed
        String b=activityModel.getSolutionPath();
        String b_new = b.replace("\\","\\\\");
        System.out.println("correct address is "+b_new);
            try{
                //Runtime.getRuntime().exec("rund1132 url.dll,FileprotocolHandler "+"U:\\CMPT150\\f2-sample.pdf");
                //Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + a.replaceAll("\\","\\\\")); 
                    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + b_new);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e,"exception", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_SolutionOpenActionPerformed

    private void GradeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GradeTableMouseClicked

        isrowselected = true;
        int row=GradeTable.getSelectedRow();
        String getGradeID=(GradeTable.getModel().getValueAt(row, 0).toString());
        String getMaxGrade=(GradeTable.getModel().getValueAt(row, 2).toString());
        MaxGrade = Integer.parseInt(getMaxGrade);
        //JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
        try{
            int GradeID=Integer.parseInt(getGradeID);
            selectedGradeID=GradeID;
            JOptionPane.showMessageDialog(null,"selected gradeID is "+selectedGradeID,"select an item", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e,"Exception", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_GradeTableMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeActivityChoose(userModel, courseModel).setVisible(true);
            }
        });
    }//GEN-LAST:event_BackActionPerformed
     
        
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GradingProblemSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GradingProblemSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GradingProblemSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GradingProblemSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GradingProblemSet().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField GradeField;
    private javax.swing.JTable GradeTable;
    private javax.swing.JButton ReviewGrade;
    private javax.swing.JButton SaveGrade1;
    private javax.swing.JButton SolutionOpen;
    private javax.swing.JButton SubmissionOpen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
